name: Build Pages

on:
  - workflow_dispatch
  # - push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nhoffman/borborygmi:latest
      options:
        --user 1001:1001
        -v "${{github.workspace}}":"${{github.workspace}}"
        -w "${{github.workspace}}"
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v3

    - name: Restore previously build pages
      id: pages-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          content
          output
          .sconsign.dblite
        key: ${{ runner.os }}-pages

    - name: Build Pages
      run: source /opt/build/venv/bin/activate && scons
      shell: bash

    - name: Deploy to GH Pages
      run: source /opt/build/venv/bin/activate && scons publish
      shell: bash

    - name: Save pages
      id: pages-save
      uses: actions/cache/save@v3
      with:
        path: |
          content
          output
          .sconsign.dblite
        key: ${{ steps.pages-restore.outputs.cache-primary-key }}

  # # https://github.com/actions/deploy-pages
  # deploy:
  #   needs: build

  #   permissions:
  #     pages: write
  #     id-token: write

  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Deploy to GitHub Pages
  #     id: deployment
  #     uses: actions/deploy-pages@v2
  #     with:
  #       artifact_name: output
