name: Build Pages

# on:
#   - workflow_dispatch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nhoffman/borborygmi:latest
      options:
        --user 1001:1001
        -v "${{github.workspace}}":"${{github.workspace}}"
        -w "${{github.workspace}}"
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v3

    - name: Restore previously build pages
      id: pages-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          content
          output
          .sconsign.dblite
        key: ${{ runner.os }}-pages

    - name: Build Pages
      run: source /opt/build/venv/bin/activate && scons
      shell: bash

    - name: Deploy to GH Pages
      run: source /opt/build/venv/bin/activate && scons publish
      shell: bash

    - name: Save pages
      id: pages-save
      uses: actions/cache/save@v3
      with:
        path: |
          content
          output
          .sconsign.dblite
        key: ${{ steps.pages-restore.outputs.cache-primary-key }}
